{% set name = "jupyter-resource-usage" %}
{% set version = "0.7.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: e53176edd7a0dce214badfa37d2d7f8540f27067011941d124ffdfe49a0d653a

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
    - hatchling
  run:
    - jupyter_server >=1.0.0,<3
    - psutil
    - python >=3.7

test:
  imports:
    - jupyter_resource_usage
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/jupyter-server/jupyter-resource-usage
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Jupyter Server Extension for monitoring Resource Usage
  description: |
    Jupyter Server Extension for monitoring Resource Usage
  dev_url: https://github.com/jupyter-server/jupyter-resource-usage

extra:
  recipe-maintainers:
    - jtpio
