{% set name = "jupyter-resource-usage" %}
{% set version = "0.7.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: ab596a1f2f6ced9e5d063f56b772d88527d2539d61831fbfb80a37f940d3e9df

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
    - hatchling
    - hatch-jupyter-builder
  run:
    - jupyter_server >=1.0.0,<3
    - psutil
    - python >=3.7

test:
  imports:
    - jupyter_resource_usage
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/jupyter-server/jupyter-resource-usage
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Jupyter Server Extension for monitoring Resource Usage
  description: |
    Jupyter Server Extension for monitoring Resource Usage
  dev_url: https://github.com/jupyter-server/jupyter-resource-usage

extra:
  recipe-maintainers:
    - jtpio
